### ISSUE TITLE
allow concurrency

### ISSUE THREAD

**Issue by Morriz** [rimusz/helm-tiller#53]
It is currently not possible to run concurrent `helm tiller run -- helm ...` commands. Any idea if that will be possible in the future? Right now I am using helmfile which can't deploy multiple charts simultaneously, nor delete them concurrently.

**Comment by rimusz** [comment]
I would recommend to run concurrent `helm tiller run -- helm ...` commands in docker containers, as making it in the plugin is out of the scope.

**Comment by Morriz** [comment]
Does that address my reported issue about concurrency? Are you suggesting multiple spun up docker containers executing commands concurrently is possible without conflicts? Then I can suggest the author of helmfile @mumoshu to do just that.

**Comment by rimusz** [comment]
if you don't do multiple releases from at the same time for the same helm release, everything will be fine

**Comment by Morriz** [comment]
great...that means concurrency is possible...why not from the plugin? why is that out of scope?

**Comment by rimusz** [comment]
as you need to run helm + pluggin per container

**Comment by rustycl0ck** [comment]
Isn't it because `helm tiller run -- helm ...` always uses a constant port for running tiller? If each `helm tiller run` would run tiller on a random port, then this problem would be solved I think. I can't even run `helm tiller start-ci && helmfile apply` in one window and `helm tiller run -- helm status my-app` in another window because the `helm tiller run` kills the `start-ci` server as well at the time of exit.

**Comment by rimusz** [comment]
as I mentioned before to get to concurrency run helm+tiller in the container.

Helm v3 is under way (very well back compatible with v2) and beta is already available that will make this plugin obsolete soon.
